### ISSUE TITLE
Trailing whitespace causes infinite loop

### ISSUE THREAD

**Issue by n0vacane** [toad1359/AIndrew#5]
try something with some spaces after it. infinite loop ensues.

**Comment by toad1359** [comment]
Output? ?

**Comment by n0vacane** [comment]
Doesn't crash now, but:

@ennui:~/Desktop/git/AIndrew$ ./run.sh 
Loading A I....
Ready for Input.
Loading Modules
hi
Salutations
hello
Greetings
  
Greetings
a  
Hola
jxcjx 
Hello
oeoeoeoe    
Salutations

**Comment by toad1359** [comment]
So no matter the input.... output is a greeting... probably just need to clear a var... Thanks!

**Comment by toad1359** [comment]
Just fixed the input always being the same but not the whitespace.... will move to that next.

**Comment by toad1359** [comment]
Fixed....
