### ISSUE TITLE
void parse mangles string

### ISSUE THREAD

**Issue by n0vacane** [toad1359/AIndrew#7]
added output code to see why parse wasnt working correctly. look how it mangles the string.

Compiling
Jar created
Running
Loading A I....
Ready for Input.		(type 'exit' to quit)
Loading Modules
Hello my name is n0vacane and I can't get this string to work right.
allparts.get(0) = Hi
allparts.get(1) = my
allparts.get(2) = nise
allparts.get(3) = is
allparts.get(4) = n0vacae
allparts.get(5) = ad
allparts.get(6) = i
allparts.get(7) = ca't
allparts.get(8) = get
allparts.get(9) = tHis
allparts.get(10) = string
allparts.get(11) = to
allparts.get(12) = work
allparts.get(13) = right.

**Comment by n0vacane** [comment]
//replace words for basics
        for (int i = 0; i < knownWords.size(); i++) {
        	for (int x = 0; x < synonyms.get(i).size(); x++) {
        		if (line.contains(synonyms.get(i).get(x))) {
        			line = line.replaceAll(synonyms.get(i).get(x), knownWords.get(i));
        		}
        	}
        }

looks like this is why. try matching only whole words maybe?

**Comment by toad1359** [comment]
What format is your input? UTF-8? Because I'll try this but why would this happen? And thanks for actively helping

**Comment by toad1359** [comment]
Ah... nAMe...nISe

**Comment by n0vacane** [comment]
you got it

**Comment by toad1359** [comment]
Sounds like a space needs to be added. "is" to " is "

**Comment by toad1359** [comment]
But why and to ad?

**Comment by n0vacane** [comment]
you have to match .contains match only on a word and not the whole string

**Comment by n0vacane** [comment]
similarly for replaceall. dont do it for the whole string

**Comment by n0vacane** [comment]
break down the line and replace what you want piece by piece, then rebuild it

**Comment by toad1359** [comment]
Yep

**Comment by toad1359** [comment]
Why n0vacane to n0vacae though

**Comment by DTSCode** [comment]
An => A

**Comment by toad1359** [comment]
Fixed
